### ISSUE TITLE
Newline_madness won't load on GEDIT

### ISSUE THREAD

**Issue by Fabelab** [jefferyto/gedit-newline-madness#1]
Hello there hope some one will answer so the title is self explanatory
I have those 2:
$ python -V
Python 2.7.18
$ gedit -V
gedit - Version 3.36.2

and i get
![Gedit_newline_madness_error](https://user-images.githubusercontent.com/7839545/108086898-28a12280-7077-11eb-9db0-d69f65a6c234.png)

**Comment by jefferyto** [comment]
gedit 3.36 uses Python 3 plugins - if you ran `python3 -V` you would see you have it installed.

**But** due to API changes in gedit 3.12, this plugin isn't compatible with 3.12 or newer. I thought I updated the readme but I guess I didn't - my apologies.
